name: Style
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  formatting-check:
    name: Code Style Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'mrover'
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: "13"
          check-path: "src"
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "."
          use-isort: false
          use-pycodestyle: true
          extra-pycodestyle-options: "--max-line-length=119"
          use-pylint: false # TODO: Would have to pip install everything for this
          use-flake8: true
          extra-flake8-options: "--max-line-length=119"
          use-black: false
          use-mypy: false
